import { EMBEDDED_FACES } from './fonts.data';

/**
 * Croscore substitutes, embedded rather than installed.
 *
 * The document is Times New Roman and the stamp renders in Arial. The Linux host has neither, and
 * Chromium does not fail on a missing font — it silently picks another and re-flows every line.
 * That would be correct in dev, wrong in prod, and already frozen into every stored file by the
 * time anyone looked. Tinos and Arimo are metrically identical to Times New Roman and Arial (same
 * advance widths, by design), so line breaks land in the same place.
 *
 * Each face is declared under the name the *document* asks for, so `font-family: "Times New Roman"`
 * in CertificateDocument resolves to the bundled bytes with no change to the component.
 *
 * The bytes live in fonts.data.ts, generated by scripts/build-fonts.mjs, rather than being read
 * from node_modules at render time: Next bundles the server with webpack, which rewrites
 * require.resolve() into a context stub that resolves nothing — the fonts would vanish inside Next
 * while working under tsx, and the failure looks like a slightly wrong document, not an error.
 *
 * Subsets are not guesswork: they are what the document's own text needs. Uzbek Cyrillic қ/ғ/ҳ
 * live in cyrillic-ext, not cyrillic — drop it and those letters alone fall back, mid-word.
 */
let cached: string | null = null;

/** `@font-face` rules with the fonts inlined as base64. */
export function fontFaceCss(): string {
  if (cached !== null) return cached;
  cached = EMBEDDED_FACES.map(
    (f) =>
      `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${f.weight};` +
      `src:url(data:font/woff2;base64,${f.woff2Base64}) format('woff2');unicode-range:${f.unicodeRange};}`,
  ).join('\n');
  return cached;
}

/** Families declared by {@link fontFaceCss} — the tripwire the tests assert against. */
export const SUBSTITUTED_FAMILIES = [...new Set(EMBEDDED_FACES.map((f) => f.family))];
