// Regenerates src/pdf/fonts.data.ts from the @fontsource packages.
//
//   node scripts/build-fonts.mjs
//
// Run this after bumping @fontsource/tinos or @fontsource/arimo, and commit the result.
//
// Why the bytes are baked into a .ts file rather than read at runtime: Next bundles the server
// with webpack, which rewrites require.resolve() into its own context stub — the font lookup then
// resolves nothing inside Next while working fine under tsx, and the document silently renders in
// a fallback font. Baking them in removes the question: there is no lookup left to break.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));

/** Croscore substitutes, declared under the name the document asks for. See src/pdf/fonts.ts. */
const SUBSTITUTES = [
  { as: 'Times New Roman', pkg: '@fontsource/tinos', slug: 'tinos', subsets: ['latin', 'cyrillic', 'cyrillic-ext'], weights: [400, 700] },
  { as: 'Arial', pkg: '@fontsource/arimo', slug: 'arimo', subsets: ['cyrillic', 'cyrillic-ext'], weights: [400, 700] },
];

const faces = [];
for (const sub of SUBSTITUTES) {
  const dir = path.dirname(require.resolve(`${sub.pkg}/package.json`));
  const ranges = JSON.parse(readFileSync(path.join(dir, 'unicode.json'), 'utf8'));
  for (const subset of sub.subsets) {
    const unicodeRange = ranges[subset];
    if (!unicodeRange) throw new Error(`${sub.pkg}: unicode.json has no subset "${subset}"`);
    for (const weight of sub.weights) {
      const file = path.join(dir, 'files', `${sub.slug}-${subset}-${weight}-normal.woff2`);
      const woff2Base64 = readFileSync(file).toString('base64');
      faces.push({ family: sub.as, weight, subset, unicodeRange, woff2Base64 });
      console.log(`${sub.as.padEnd(16)} ${String(weight).padEnd(4)} ${subset.padEnd(13)} ${(woff2Base64.length / 1024).toFixed(1)} KB`);
    }
  }
}

const out = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
// Regenerate after bumping @fontsource/tinos or @fontsource/arimo.
export interface EmbeddedFace {
  /** The family name the document asks for; the bytes are the metric-compatible substitute. */
  family: string;
  weight: number;
  subset: string;
  unicodeRange: string;
  woff2Base64: string;
}

export const EMBEDDED_FACES: EmbeddedFace[] = ${JSON.stringify(faces, null, 2)};
`;

const target = path.join(here, '..', 'src', 'pdf', 'fonts.data.ts');
writeFileSync(target, out);
console.log(`\n-> ${path.relative(process.cwd(), target)}  (${(out.length / 1024).toFixed(0)} KB, ${faces.length} face)`);
